development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: spotippos
  username: root
  password:
test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: spotippos_test
  username: root
  password:
