development:
  adapter: mysql2
  encoding: utf8
  host: db
  database: spotippos
  username: root
  password:
test:
  adapter: mysql2
  encoding: utf8
  host: db
  database: spotippos_test
  username: root
  password:
